export type TranslationKeys = 'contact' | 'profile' | 'greenPurple' | 'createdBy'
    | 'profileDescription' | 'myAccounts' | 'bluePink' | 'lightTheme' | 'author' | 'seeOnGithub' | 'createdAt' | 'lastCommit'
    | 'seeRepositoryOnGithub' | 'seeUserOnGithub' | 'langCode' | 'langName' | 'projects' | 'myProjects'
    | 'repositoryLinkCopiedToClipboard' | 'langDirection' | 'softwareDeveloper' | 'openDrawer' | 'closeDrawer' | 'technicalSchool'
    | 'university' | 'downloadResume' | 'seeInNewTabResume' | 'techStack' | 'resume' | 'langISO' | 'education' | 'resumeLoadingError'
    | 'showModelIn3D' | 'universitySpecialization' | 'universityStart' | 'universityEnd' | 'mechatronics' | 'technicalSchoolStart'
    | 'technicalSchoolEnd' | 'loadingIsTakingTooLong' | 'now' | 'technicalSchoolDescription' | 'universityDescription' | 'inProgress'
    | 'experience' | 'fssDescription' | 'intership' | 'keyProjects' | 'comercialExperience' | 'errorLoadingUsers' | 'errorLoadingProjects'
    | 'noneComersialExperience' | 'reactDescription' | 'vueDescription' | 'nodeDescription' | 'sqlDescription' | 'netDescription'
    | 'cicdDescription' | 'unityDescription' | 'pythonDescription' | 'mongoDescription' | 'azureDescription';

export type OptionalTranslationKeys = 'authorName';

export type RequiredTranslationKeys = Exclude<TranslationKeys, OptionalTranslationKeys>;

export type LanguageDictionary = {
    [key in RequiredTranslationKeys]: string;
} & {
        [key in OptionalTranslationKeys]?: string;
    };


export type DictionaryType = {
    [key: string]: LanguageDictionary;
};

export const dictionary: DictionaryType = {
    pl: {
        langCode: 'pl',
        langName: 'Polski',
        langDirection: 'ltr',
        contact: 'Kontakt',
        profile: 'Profil',
        projects: 'Projekty',
        greenPurple: 'Zielono-fioletowy',
        bluePink: 'Niebiesko-różowy',
        myProjects: 'Moje projekty',
        lightTheme: 'Jasny motyw',
        createdBy: 'Stworzone przez',
        profileDescription: 'Jestem absolwentem studiów inżynierskich na kierunku Inżynieria Oprogramowania na Uniwersytecie Bielsko-Biała – dyplom otrzymam w marcu. Posiadam roczne komercyjne doświadczenie w tworzeniu aplikacji webowych (JavaScript, React, Node.js, Vue.js) oraz desktopowych (C#, WPF, Unity). Pracowałem z różnymi bazami danych (MySQL, SQL Server, MongoDB) oraz narzędziami DevOps (Docker, Azure DevOps). Obecnie szukam pracy na pełny etat, dostępny do rozpoczęcia współpracy od zaraz, aby rozwijać swoje umiejętności i zdobywać doświadczenie zawodowe.',
        myAccounts: 'Moje konta',
        author: 'Adriana Raszka',
        seeOnGithub: 'Zobacz na Githubie',
        createdAt: 'Utworzono',
        lastCommit: 'Ostatni commit',
        seeRepositoryOnGithub: 'Zobacz repozytorium na Githubie',
        seeUserOnGithub: 'Zobacz użytkownika na Githubie',
        repositoryLinkCopiedToClipboard: 'Link do repozytorium został skopiowany do schowka',
        softwareDeveloper: 'Programista oprogramowania',
        openDrawer: 'Otwórz szufladę',
        closeDrawer: 'Zamknij szufladę',
        technicalSchool: 'Technikum Mechatroniczne',
        university: 'Uniwersytet Bielsko-Biała',
        downloadResume: 'Pobierz CV',
        seeInNewTabResume: 'Zobacz CV w nowej karcie',
        techStack: 'Technologie',
        resume: 'CV',
        langISO: 'pl-PL',
        education: 'Edukacja',
        resumeLoadingError: 'Wystąpił błąd podczas ładowania CV',
        showModelIn3D: 'Pokaż model w 3D',
        universitySpecialization: 'Specjalizacja',
        universityStart: 'Rozpoczęcie',
        universityEnd: 'Zakończenie',
        mechatronics: 'Mechatronika',
        technicalSchoolStart: 'Początek technikum',
        technicalSchoolEnd: 'Koniec technikum',
        loadingIsTakingTooLong: 'Ładowanie trwa powyżej',
        now: 'teraz',
        technicalSchoolDescription: "Jako absolwent technikum o specjalizacji Mechatronika zdobyłem wszechstronną wiedzę i praktyczne umiejętności z zakresu elektroniki, elektryki oraz programowania sterowników PLC. Program nauczania zapewnił solidne podstawy w tych obszarach, kładąc nacisk na szkolenie praktyczne i zastosowania w rzeczywistości. Edukacja ta wyposażyła mnie w umiejętność rozumienia i rozwiązywania złożonych problemów technicznych, projektowania i programowania sterowników PLC oraz efektywnego działania w dziedzinie mechatroniki.",
        universityDescription: "W trakcie studiów na Uniwersytecie zdobyłem obszerną wiedzę i praktyczne doświadczenie w różnych językach programowania i technologiach. Opanowałem C++ i C#, a także zapoznałem się z technologiami .Net, takimi jak ASP.NET i WPF. Ponadto zgłębiłem programowanie PLC, co dodatkowo poszerzyło moje umiejętności techniczne. Ponadto nauczyłem się tworzyć strony internetowe za pomocą React oraz zarządzać bazami danych SQL. To wszechstronne wykształcenie wyposażyło mnie w różnorodny zestaw umiejętności, umożliwiając mi radzenie sobie z złożonymi wyzwaniami związanymi z rozwojem oprogramowania oraz efektywne działanie w dziedzinie informatyki.",
        inProgress: 'W trakcie rozwoju',
        comercialExperience: "+1 rok doświadczenia komercyjnego",
        fssDescription: 'Podczas mojej pracy jako Frontend Developer pracowałem intensywnie z React, Vue.js, Node.js oraz SQL. Korzystałem z narzędzi do kontroli wersji takich jak GitHub i GitLab oraz zarządzałem zadaniami projektowymi przy pomocy Jira. Jednym z kluczowych projektów, nad którym pracowałem, była aplikacja dla Jachtów. W ramach tego projektu byłem odpowiedzialny za tworzenie interaktywnych map, na których użytkownicy mogli tworzyć i śledzić trasy.Dodatkowo, zintegrowałem dane pogodowe z zewnętrznego API, które były wyświetlane w aplikacji.Zajmowałem się także przepływem danych z czujników: dane z czujników były przesyłane do InfluxDB, z której tworzyłem wykresy w czasie rzeczywistym i wskaźniki, takie jak bieżąca prędkość i inne istotne metryki dla użytkowników na jachcie.',
        intership: 'Mimo że moje stanowisko było stażem, powierzono mi pracę nad rzeczywistymi projektami i dostarczanie realnych wyników. Zyskałem praktyczne doświadczenie w C# i ASP.NET Core API. Do moich zadań należało pisanie testów jednostkowych, testów integracyjnych oraz zapewnienie kompatybilności projektów z kontenerami Docker do testowania i uruchamiania aplikacji. Jedną z głównych aplikacji, nad którą pracowałem, była aplikacja oparta na WPF, służąca do obsługi skanerów kodów kreskowych.Byłem odpowiedzialny za wprowadzanie zmian, poprawek błędów oraz aktualizowanie wersji aplikacji, by poprawić jej wydajność.Dodatkowo stworzyłem symulatory skanerów, które później były wykorzystywane w fazie testowania, zapewniając, że procesy skanowania zostały dokładnie zwalidowane.',
        keyProjects: 'Kluczowe projekty',
        experience: "Doświadczenie",
        errorLoadingProjects: 'Wystąpił błąd podczas ładowania projektów',
        errorLoadingUsers: 'Wystąpił błąd podczas ładowania użytkowników',
        noneComersialExperience: "+5 lata nie komercyjnego doświadczenia",
        reactDescription: 'Posiadam komercyjne doświadczenie w React, gdzie tworzyłem mini-gry dla nowoczesnej platformy rozrywkowej oraz aplikację dla jachtów. Wykorzystywałem w niej mapy, API, rysowanie na canvasie, przesyłanie zdjęć i obsługę elementów 3D na serwerze. Używałem także Redux do zarządzania stanem oraz Material UI do stylizacji.',
        vueDescription: 'Pracowałem komercyjnie z Vue 3, gdzie brałem udział w migracji systemu opartego na PHP na Vue + Node.js. Moim głównym zadaniem było tworzenie interfejsu użytkownika, generowanie PDF-ów oraz funkcjonalności do zarządzania załogą. Korzystałem z Pinia do zarządzania stanem oraz Vuetify do komponentów UI.',
        nodeDescription: 'Tworzyłem prosty serwer backendowy, który komunikował się z bazami danych MySQL i InfluxDB (do przechowywania i odczytu danych z czujników). Implementowałem repozytoria, serwisy i obsługę requestów. Posiadam komercyjne doświadczenie w Node.js.',
        sqlDescription: 'Komercyjnie używałem SQL, gdzie tworzyłem proste zapytania, joiny i subquery. Na studiach pracowałem z T-SQL w Microsoft SQL Server, gdzie tworzyłem widoki, kursory i zarządzałem bazami danych.',
        cicdDescription: 'Podczas stażu pracowałem z CI/CD w Azure DevOps, gdzie konfigurowałem pipelines dla aplikacji WPF. Dodatkowo stworzyłem Docker Compose, który uruchamiał bazy danych i serwery dla środowiska deweloperskiego, a także zintegrowałem go z SEQ do logowania. Do testów używaliśmy Docker containers.',
        netDescription: 'Posiadam komercyjne doświadczenie w .NET, gdzie pisałem testy jednostkowe i integracyjne dla ASP.NET API, dodawałem nowe funkcjonalności i naprawiałem błędy. Pracowałem także z WPF do aplikacji desktopowych, tworząc symulatory skanerów na potrzeby testów, a także wykonywałem drobne poprawki i refaktoryzację kodu.',
        pythonDescription: 'Napisałem prostą aplikację do obsługi grafów w Pythonie z wykorzystaniem Tkinter, która pozwalała na tworzenie, edytowanie i porównywanie grafów. Był to projekt prywatny, niekomercyjny.',
        unityDescription: 'Na potrzeby pracy inżynierskiej stworzyłem grę RTS (Real-Time Strategy) w 3D, w której można budować bazę, szkolić jednostki, zarządzać ekonomią i walczyć. Gra posiada tryb multiplayer.',
        azureDescription: 'Niekomercyjnie wdrożyłem aplikacje na Azure, korzystając z App Service, SQL Database, Redis i Key Vault.',
        mongoDescription: 'Tworzyłem aplikacje w Node.js z wykorzystaniem MongoDB, używając Mongoose do tworzenia modeli, transakcji i innych operacji na bazie danych. Był to projekt prywatny, niekomercyjny.'
    },
    us: {
        langCode: 'us',
        langName: 'English',
        langDirection: 'ltr',
        contact: 'Contact',
        profile: 'Profile',
        projects: 'Projects',
        greenPurple: 'Green-purple',
        bluePink: 'Blue-pink',
        myProjects: 'My projects',
        lightTheme: 'Light theme',
        createdBy: 'Created by',
        profileDescription: 'I am a graduate of Software Engineering at the University of Bielsko-Biała – I will receive my diploma in March. I have one year of commercial experience in developing web applications (JavaScript, React, Node.js, Vue.js) and desktop applications (C#, WPF, Unity). I have worked with various databases (MySQL, SQL Server, MongoDB) and DevOps tools (Docker, Azure DevOps). I am currently looking for full-time job, available to start immediately, to further develop my skills and gain professional experience.',
        myAccounts: 'My accounts',
        author: 'Adrian Raszka',
        seeOnGithub: 'See on Github',
        createdAt: 'Created at',
        lastCommit: 'Last commit',
        seeRepositoryOnGithub: 'See repository on Github',
        seeUserOnGithub: 'See user on Github',
        repositoryLinkCopiedToClipboard: 'Repository link copied to clipboard',
        softwareDeveloper: 'Software developer',
        openDrawer: 'Open drawer',
        closeDrawer: 'Close drawer',
        technicalSchool: 'Technical Mechatronics School',
        university: 'University of Bielsko-Biała',
        downloadResume: 'Download CV',
        seeInNewTabResume: 'See CV in new tab',
        techStack: 'Technologies',
        resume: 'Resume',
        langISO: 'en-US',
        education: 'Education',
        resumeLoadingError: 'An error occurred while loading the resume',
        showModelIn3D: 'Show model in 3D',
        universitySpecialization: 'Specialization',
        universityEnd: 'End',
        universityStart: 'Start',
        mechatronics: 'Mechatronics',
        technicalSchoolStart: 'Technical school start',
        technicalSchoolEnd: 'Technical school end',
        loadingIsTakingTooLong: 'Loading is taking above',
        authorName: 'Adrian Raszka',
        now: 'now',
        technicalSchoolDescription: "As a graduate of a technical school specializing in Mechatronics, I have gained comprehensive knowledge and practical skills in electronics, electricity, and Programmable Logic Controller (PLC) programming. The curriculum provided a strong foundation in these areas, emphasizing hands-on training and real-world applications. This education has equipped me with the ability to understand and solve complex technical problems, design and program PLC controllers, and contribute effectively in the field of Mechatronics.",
        universityDescription: "During my studies at the University, I gained extensive knowledge and practical experience in various programming languages and technologies. I mastered C++ and C#, and got acquainted with .Net technologies such as ASP.NET and WPF. I also delved into PLC programming, which further broadened my technical skills. In addition, I learned how to create web pages using React and manage SQL databases. This comprehensive education has equipped me with a diverse set of skills, enabling me to tackle complex software development challenges and contribute effectively in the field of computer science.",
        inProgress: 'In progress',
        comercialExperience: "+1 year of commercial experience",
        fssDescription: 'During my time as a Frontend Developer, I worked extensively with React, Vue.js, Node.js, and SQL. I utilized version control tools such as GitHub and GitLab and managed project tasks using Jira. One of my key projects involved developing a Yacht Application. In this project, I was responsible for building interactive maps where users could create and track routes.Additionally, I integrated weather data from an external API, which was displayed within the application.I also worked on the data flow from sensor readings: the sensor data was passed to InfluxDB, from which I created real- time graphs and indicators, such as current speed and other relevant metrics for users on the yacht.',
        intership: 'Even though my role was an internship, I was entrusted with working on real-world projects and delivering meaningful results. I gained hands-on experience in C# and ASP.NET Core API development. My tasks included writing unit tests, integration tests, and ensuring the compatibility of the projects with Docker containers for both testing and running the application. One of the major applications I worked on was a WPF- based application used for handling barcode scanners.I was responsible for implementing various changes, bug fixes, and version updates to improve its performance.Additionally, I developed scanner simulators that were later used in the testing phase, ensuring that the scanning processes were thoroughly validated.',
        keyProjects: 'Key projects',
        experience: "Experience",
        errorLoadingProjects: 'An error occurred while loading projects',
        errorLoadingUsers: 'An error occurred while loading users',
        noneComersialExperience: "+5 years of non-commercial experience",
        reactDescription: 'I have commercial experience with React, where I developed mini-games for a modern entertainment platform and an application for yachts. In this project, I worked with maps, APIs, canvas-based drawing, image uploads, and handling 3D elements on a server. I also utilized Redux for state management and Material UI for styling.',
        vueDescription: 'I worked with Vue 3 in a commercial project, migrating a PHP-based system to a Vue + Node.js stack. My main responsibilities included UI development, PDF generation, and crew management functionalities. I used Pinia for state management and Vuetify for UI components.',
        nodeDescription: 'I developed a simple backend server that interacted with MySQL and InfluxDB (for sensor data storage and retrieval). I implemented repositories, services, and handled API requests. I have commercial experience with Node.js.',
        sqlDescription: 'I have used SQL commercially, creating simple queries, joins, and subqueries. During my studies, I worked with T-SQL in Microsoft SQL Server, creating views, cursors, and managing databases.',
        azureDescription: 'I deployed applications on Azure non-commercially, using App Service, SQL Database, Redis, and Key Vault.',
        cicdDescription: 'I worked with CI/CD in Azure DevOps during my internship, configuring pipelines for WPF applications. I also created a Docker Compose that launched databases and servers for the development environment, and integrated it with SEQ for logging. We used Docker containers for testing.',
        mongoDescription: 'I developed applications in Node.js using MongoDB non-commercially, using Mongoose for creating models, transactions, and other database operations.',
        netDescription: 'I have commercial experience with .NET, writing unit and integration tests for ASP.NET APIs, adding new features, and fixing bugs. I also worked with WPF for desktop applications, creating scanner simulators for testing purposes, and performing minor code fixes and refactoring.',
        pythonDescription: 'I developed a simple graph application in Python using Tkinter, allowing users to create, edit, and compare graphs. This was a private, non-commercial project.',
        unityDescription: 'For my diploma, I created a 3D Real-Time Strategy (RTS) game where players could build a base, train units, manage economy, and fight. The game features a multiplayer mode.',
    },
    sp: {
        langCode: 'sp',
        langName: 'Español',
        langDirection: 'ltr',
        contact: 'Contacto',
        profile: 'Perfil',
        projects: 'Proyectos',
        greenPurple: 'Verde-púrpura',
        bluePink: 'Azul-rosa',
        myProjects: 'Mis proyectos',
        lightTheme: 'Tema claro',
        createdBy: 'Creado por',
        profileDescription: 'Estudiante de 7º año a tiempo completo del programa de Ingeniería de Software en la Universidad de Bielsko-Biała. Tengo experiencia en el desarrollo de aplicaciones web (JavaScript, React, Node.js, Vue.js) y aplicaciones de escritorio (C#, WPF, Unity). He trabajado con varias bases de datos (MySQL, SQL Server, MongoDB) y herramientas de DevOps (Docker, Azure DevOps). Busco un trabajo de medio tiempo flexible (a tiempo completo disponible a partir de septiembre) para adquirir experiencia profesional y desarrollar mis habilidades.',
        myAccounts: 'Mis cuentas',
        author: 'Adrian Raszka',
        seeOnGithub: 'Ver en Github',
        createdAt: 'Creado en',
        lastCommit: 'Último commit',
        seeRepositoryOnGithub: 'Ver repositorio en Github',
        seeUserOnGithub: 'Ver usuario en Github',
        repositoryLinkCopiedToClipboard: 'Enlace del repositorio copiado al portapapeles',
        softwareDeveloper: 'Desarrollador de software',
        closeDrawer: 'Cerrar cajón',
        openDrawer: 'Abrir cajón',
        technicalSchool: 'Escuela Técnica de Mecatrónica',
        university: 'Universidad de Bielsko-Biała',
        downloadResume: 'Descargar CV',
        seeInNewTabResume: 'Ver CV en nueva pestaña',
        techStack: 'Tecnologías',
        resume: 'CV',
        langISO: 'es-ES',
        education: 'Educación',
        resumeLoadingError: 'Se produjo un error al cargar el CV',
        showModelIn3D: 'Mostrar modelo en 3D',
        universitySpecialization: 'Especialización',
        universityStart: 'Inicio',
        universityEnd: 'Fin',
        mechatronics: 'Mecatrónica',
        technicalSchoolStart: 'Inicio de la escuela técnica',
        technicalSchoolEnd: 'Fin de la escuela técnica',
        loadingIsTakingTooLong: 'La carga está tomando más de',
        now: 'ahora',
        technicalSchoolDescription: "Como graduado de una escuela técnica especializada en Mecatrónica, he adquirido conocimientos y habilidades prácticas en electrónica, electricidad y programación de controladores lógicos programables (PLC). El plan de estudios proporcionó una sólida base en estas áreas, enfatizando la capacitación práctica y las aplicaciones del mundo real. Esta educación me ha dotado de la capacidad de comprender y resolver problemas técnicos complejos, diseñar y programar controladores PLC y contribuir eficazmente en el campo de la Mecatrónica.",
        universityDescription: "Durante mis estudios en la Universidad, adquirí amplios conocimientos y experiencia práctica en varios lenguajes de programación y tecnologías. Dominé C++ y C#, y me familiaricé con tecnologías .Net como ASP.NET y WPF. También profundicé en la programación de PLC, lo que amplió aún más mis habilidades técnicas. Además, aprendí a crear páginas web con React y a gestionar bases de datos SQL. Esta educación integral me ha dotado de un conjunto diverso de habilidades, lo que me permite abordar desafíos complejos de desarrollo de software y contribuir eficazmente en el campo de la informática.",
        inProgress: 'En progreso',
        comercialExperience: "+1 año de experiencia comercial",
        fssDescription: 'Durante mi tiempo como Desarrollador Frontend, trabajé ampliamente con React, Vue.js, Node.js y SQL. Utilicé herramientas de control de versiones como GitHub y GitLab y gestioné tareas del proyecto usando Jira. Uno de mis proyectos clave fue el desarrollo de una aplicación para yates. En este proyecto, fui responsable de crear mapas interactivos donde los usuarios podían crear y seguir rutas. Además, integré datos meteorológicos de una API externa, que se mostraban dentro de la aplicación. También trabajé en el flujo de datos de sensores: los datos de los sensores se enviaban a InfluxDB, desde donde creaba gráficos en tiempo real e indicadores, como la velocidad actual y otras métricas relevantes para los usuarios en el yate.',
        intership: 'Aunque mi puesto fue una pasantía, se me confió trabajar en proyectos reales y entregar resultados significativos. Adquirí experiencia práctica en C# y ASP.NET Core API. Mis tareas incluían escribir pruebas unitarias, pruebas de integración y asegurar la compatibilidad de los proyectos con contenedores Docker para pruebas y ejecución de la aplicación. Una de las aplicaciones principales en las que trabajé fue una aplicación basada en WPF utilizada para manejar escáneres de códigos de barras.Fui responsable de implementar varios cambios, corrección de errores y actualizaciones de versiones para mejorar su rendimiento.Además, desarrollé simuladores de escáneres que luego se utilizaron en la fase de prueba para asegurar que los procesos de escaneo fueran validados correctamente.',
        keyProjects: 'Proyectos clave',
        experience: "Experiencia",
        errorLoadingProjects: 'Se produjo un error al cargar los proyectos',
        errorLoadingUsers: 'Se produjo un error al cargar los usuarios',
        noneComersialExperience: "+5 años de experiencia no comercial",
        azureDescription: 'Implementé aplicaciones en Azure no comercialmente, utilizando App Service, SQL Database, Redis y Key Vault.',
        cicdDescription: 'Trabajé con CI/CD en Azure DevOps durante mi pasantía, configurando pipelines para aplicaciones WPF. También creé un Docker Compose que lanzaba bases de datos y servidores para el entorno de desarrollo, e integré SEQ para el registro. Utilizamos contenedores Docker para pruebas.',
        mongoDescription: 'Desarrollé aplicaciones en Node.js utilizando MongoDB no comercialmente, utilizando Mongoose para crear modelos, transacciones y otras operaciones de base de datos.',
        netDescription: 'Tengo experiencia comercial con .NET, escribiendo pruebas unitarias e integración para APIs ASP.NET, agregando nuevas funcionalidades y corrigiendo errores. También trabajé con WPF para aplicaciones de escritorio, creando simuladores de escáneres para pruebas y realizando correcciones menores y refactorizaciones de código.',
        pythonDescription: 'Desarrollé una aplicación de gráficos simples en Python con Tkinter, que permitía a los usuarios crear, editar y comparar gráficos. Este fue un proyecto privado, no comercial.',
        unityDescription: 'Para mi tesis, creé un juego de estrategia en tiempo real (RTS) en 3D donde los jugadores podían construir una base, entrenar unidades, gestionar la economía y luchar. El juego cuenta con un modo multijugador.',
        reactDescription: 'Tengo experiencia comercial con React, donde desarrollé mini-juegos para una plataforma de entretenimiento moderna y una aplicación para yates. En este proyecto, trabajé con mapas, APIs, dibujo en canvas, carga de imágenes y manejo de elementos 3D en un servidor. También utilicé Redux para la gestión de estado y Material UI para el estilo.',
        vueDescription: 'Trabajé con Vue 3 en un proyecto comercial, migrando un sistema basado en PHP a una pila Vue + Node.js. Mis principales responsabilidades incluyeron el desarrollo de la interfaz de usuario, la generación de PDF y las funcionalidades de gestión de tripulación. Usé Pinia para la gestión de estado y Vuetify para los componentes de la interfaz de usuario.',
        nodeDescription: 'Desarrollé un servidor backend simple que interactuaba con MySQL e InfluxDB (para el almacenamiento y recuperación de datos de sensores). Implementé repositorios, servicios y manejé solicitudes de API. Tengo experiencia comercial con Node.js.',
        sqlDescription: 'He utilizado SQL comercialmente, creando consultas simples, joins y subconsultas. Durante mis estudios, trabajé con T-SQL en Microsoft SQL Server, creando vistas, cursores y gestionando bases de datos.',
    },
    sa: {
        langCode: 'sa',
        langName: 'العربية',
        langDirection: 'rtl',
        contact: 'اتصل',
        profile: 'الملف الشخصي',
        projects: 'مشاريع',
        greenPurple: 'أخضر-أرجواني',
        bluePink: 'أزرق-وردي',
        myProjects: 'مشاريعي',
        lightTheme: 'موضوع الضوء',
        createdBy: 'أنشئ بواسطة',
        profileDescription: 'سابع عام في برنامج الهندسة البرمجية بدوام كامل في جامعة بيلسكو-بياوا. لدي خبرة في تطوير تطبيقات الويب (JavaScript، React، Node.js، Vue.js) وتطبيقات سطح المكتب (C#، WPF، Unity). عملت مع قواعد بيانات مختلفة (MySQL، SQL Server، MongoDB) وأدوات DevOps (Docker، Azure DevOps). ابحث عن عمل بدوام جزئي مرن (يمكنني العمل بدوام كامل في سبتمبر) لاكتساب الخبرة المهنية وتطوير مهاراتي.',
        myAccounts: 'حساباتي',
        author: 'أدريان راسزكا',
        seeOnGithub: 'انظر على Github',
        createdAt: 'أنشئت في',
        lastCommit: 'آخر التزام',
        seeRepositoryOnGithub: 'انظر المستودع على Github',
        seeUserOnGithub: 'انظر المستخدم على Github',
        repositoryLinkCopiedToClipboard: 'تم نسخ رابط المستودع إلى الحافظة',
        softwareDeveloper: 'مطور برامج',
        closeDrawer: 'إغلاق الدرج',
        openDrawer: 'فتح الدرج',
        technicalSchool: 'المدرسة التقنية للميكاترونيك',
        university: 'جامعة بيلسكو-بيالا',
        downloadResume: 'تحميل السيرة الذاتية',
        seeInNewTabResume: 'انظر السيرة الذاتية في علامة تبويب جديدة',
        techStack: 'التكنولوجيا',
        resume: 'السيرة الذاتية',
        langISO: 'ar-SA',
        education: 'التعليم',
        resumeLoadingError: 'حدث خطأ أثناء تحميل السيرة الذاتية',
        showModelIn3D: 'عرض النموذج ثلاثي الأبعاد',
        universitySpecialization: 'تخصص',
        universityStart: 'بداية',
        universityEnd: 'نهاية',
        mechatronics: 'الميكاترونيات',
        technicalSchoolStart: 'بداية المدرسة التقنية',
        technicalSchoolEnd: 'نهاية المدرسة التقنية',
        loadingIsTakingTooLong: 'التحميل يستغرق أكثر من',
        now: 'الآن',
        technicalSchoolDescription: "كخريج من المدرسة التقنية المتخصصة في الميكاترونيك، اكتسبت معرفة شاملة ومهارات عملية في الإلكترونيات والكهرباء وبرمجة المتحكمات المنطقية القابلة للبرمجة (PLC). قدم المنهج الدراسي أساسًا قويًا في هذه المجالات، مع التركيز على التدريب العملي والتطبيقات العملية. هذا التعليم قد زودني بالقدرة على فهم وحل المشاكل التقنية المعقدة، وتصميم وبرمجة متحكمات PLC، والمساهمة بفعالية في مجال الميكاترونيك.",
        universityDescription: "خلال دراستي في الجامعة، اكتسبت معرفة وخبرة عملية واسعة في لغات البرمجة والتقنيات المختلفة. تقنمت في C++ و C#، وتعرفت على تقنيات .Net مثل ASP.NET و WPF. كما تعمقت في برمجة PLC، مما زاد من مهاراتي التقنية. بالإضافة إلى ذلك، تعلمت كيفية إنشاء صفحات ويب باستخدام React وإدارة قواعد بيانات SQL. هذا التعليم الشامل قد زودني بمجموعة متنوعة من المهارات، مما يمكنني من التعامل مع تحديات تطوير البرمجيات المعقدة والمساهمة بفعالية في مجال علوم الكمبيوتر.",
        inProgress: 'قيد التطوير',
        comercialExperience: "+1 سنة من الخبرة التجارية",
        fssDescription: 'خلال عملي كـ مطور واجهة أمامية، كنت أعمل بشكل مكثف مع React و Vue.js و Node.js و SQL. كنت أستخدم أدوات التحكم في الإصدارات مثل GitHub و GitLab وأدير المهام باستخدام Jira. أحد المشاريع الرئيسية التي عملت عليها كان تطبيق لــ اليخوت. في هذا المشروع، كنت مسؤولاً عن إنشاء خرائط تفاعلية حيث يمكن للمستخدمين إنشاء وتتبع المسارات.بالإضافة إلى ذلك، قمت بدمج بيانات الطقس من API خارجي يتم عرضها داخل التطبيق.كما كنت أتعامل مع تدفق البيانات من أجهزة الاستشعار: حيث يتم إرسال بيانات الاستشعار إلى InfluxDB، والتي قمت من خلالها بإنشاء رسوم بيانية حية ومؤشرات، مثل السرعة الحالية وغيرها من القياسات المهمة للمستخدمين على اليخت.',
        intership: 'على الرغم من أن هذا كان تدريبًا داخليًا، تم تكليفي بالعمل على مشاريع حقيقية وتقديم نتائج حقيقية. حصلت على تجربة عملية في C# و ASP.NET Core API. كانت مهمتي كتابة اختبارات الوحدات و الاختبارات التكاملية وضمان توافق المشاريع مع حاويات Docker للاختبار وتشغيل التطبيق.أحد التطبيقات الرئيسية التي عملت عليها كان تطبيقًا يعتمد على WPF لإدارة ماسحات الباركود.كنت مسؤولاً عن إدخال تغييرات وإصلاح الأخطاء وتحديث الإصدارات لتحسين أدائه.بالإضافة إلى ذلك، قمت بتطوير محاكيات للماسحات الضوئية التي تم استخدامها لاحقًا في مرحلة الاختبار لضمان التحقق الدقيق من عمليات المسح.',
        keyProjects: 'المشاريع الرئيسية',
        experience: "الخبرة",
        errorLoadingProjects: 'حدث خطأ أثناء تحميل المشاريع',
        errorLoadingUsers: 'حدث خطأ أثناء تحميل المستخدمين',
        noneComersialExperience: "+5 سنوات من الخبرة غير التجارية",
        azureDescription: 'نفذت التطبيقات على Azure غير تجاريًا، باستخدام App Service و SQL Database و Redis و Key Vault.',
        cicdDescription: 'عملت مع CI/CD في Azure DevOps خلال فترة التدريب، وقمت بتكوين خطوط الأنابيب لتطبيقات WPF. كما قمت بإنشاء Docker Compose الذي يطلق قواعد البيانات والخوادم لبيئة التطوير، وقمت بدمجه مع SEQ لتسجيل الأحداث. استخدمنا حاويات Docker للاختبار.',
        mongoDescription: 'طورت تطبيقات في Node.js باستخدام MongoDB غير تجاريًا، باستخدام Mongoose لإنشاء نماذج والمعاملات وغيرها من العمليات على قاعدة البيانات.',
        netDescription: 'لدي خبرة تجارية في .NET، حيث كتبت اختبارات وحدية واختبارات تكاملية لواجهات برمجة التطبيقات ASP.NET، وأضفت ميزات جديدة وأصلحت الأخطاء. كما عملت أيضًا مع WPF لتطبيقات سطح المكتب، وأنشأت محاكيات لماسحات الباركود لأغراض الاختبار، وقمت بإجراء تصحيحات برمجية بسيطة وإعادة تنظيم الكود.',
        pythonDescription: 'طورت تطبيقًا بسيطًا للرسوم البيانية في Python باستخدام Tkinter، مما يتيح للمستخدمين إنشاء وتحرير ومقارنة الرسوم البيانية. كان هذا مشروعًا خاصًا غير تجاري.',
        unityDescription: 'لرسالتي، قمت بإنشاء لعبة استراتيجية ثلاثية الأبعاد في الوقت الحقيقي (RTS) حيث يمكن للاعبين بناء قاعدة وتدريب الوحدات وإدارة الاقتصاد والقتال. تتضمن اللعبة وضعًا متعدد اللاعبين.',
        reactDescription: 'لدي خبرة تجارية مع React، حيث قمت بتطوير ألعاب صغيرة لمنصة ترفيهية حديثة وتطبيق لليخوت. في هذا المشروع، عملت مع الخرائط وواجهات البرمجة التطبيقية والرسم على اللوحة وتحميل الصور ومعالجة العناصر ثلاثية الأبعاد على الخادم. كما استخدمت Redux لإدارة الحالة و Material UI للتصميم.',
        vueDescription: 'عملت مع Vue 3 في مشروع تجاري، حيث قمت بتحويل نظام مبني على PHP إلى مكدس Vue + Node.js. كانت مسؤولياتي الرئيسية تطوير واجهة المستخدم وإنشاء PDF ووظائف إدارة الطاقم. استخدمت Pinia لإدارة الحالة و Vuetify لمكونات واجهة المستخدم.',
        nodeDescription: 'طورت خادمًا خلفيًا بسيطًا تفاعل مع MySQL و InfluxDB (لتخزين واسترداد بيانات الاستشعار). نفذت مستودعات وخدمات وأدارت طلبات API. لدي خبرة تجارية في Node.js.',
        sqlDescription: 'لدي خبرة تجارية في استخدام SQL، حيث أنشأت استعلامات بسيطة وانضمامات واستعلامات فرعية. خلال دراستي، عملت مع T-SQL في Microsoft SQL Server، حيث أنشأت عروضًا ومؤشرات وأدارت قواعد البيانات.',
    },
}