export type TranslationKeys = 'contact' | 'profile' | 'greenPurple' | 'createdBy'
    | 'profileDescription' | 'myAccounts' | 'bluePink' | 'lightTheme' | 'author' | 'seeOnGithub' | 'createdAt' | 'lastCommit'
    | 'seeRepositoryOnGithub' | 'seeUserOnGithub' | 'langCode' | 'langName' | 'projects' | 'myProjects'
    | 'repositoryLinkCopiedToClipboard' | 'langDirection' | 'softwareDdeveloper' | 'openDrawer' | 'closeDrawer' | 'technicalSchool'
    | 'university' | 'downloadResume' | 'seeInNewTabResume' | 'techStack' | 'resume' | 'langISO' | 'education' | 'resumeLoadingError'
    | 'showModelIn3D' | 'universitySpecialization' | 'universityStart' | 'universityEnd' | 'mechatronics' | 'technicalSchoolStart'
    | 'technicalSchoolEnd' | 'loadingIsTakingTooLong';

export type LanguageDictionary = {
    [key in TranslationKeys]: string;
};

export type DictionaryType = {
    [key: string]: LanguageDictionary;
};

export const dictionary: DictionaryType = {
    pl: {
        langCode: 'pl',
        langName: 'Polski',
        langDirection: 'ltr',
        contact: 'Kontakt',
        profile: 'Profil',
        projects: 'Projekty',
        greenPurple: 'Zielono-fioletowy',
        bluePink: 'Niebiesko-różowy',
        myProjects: 'Moje projekty',
        lightTheme: 'Jasny motyw',
        createdBy: 'Stworzone przez',
        profileDescription: 'Jestem studentem informatyki na Politechnice Wrocławskiej. Interesuję się programowaniem, grafiką komputerową i fotografią.',
        myAccounts: 'Moje konta',
        author: 'Adriana Raszka',
        seeOnGithub: 'Zobacz na Githubie',
        createdAt: 'Utworzono',
        lastCommit: 'Ostatni commit',
        seeRepositoryOnGithub: 'Zobacz repozytorium na Githubie',
        seeUserOnGithub: 'Zobacz użytkownika na Githubie',
        repositoryLinkCopiedToClipboard: 'Link do repozytorium został skopiowany do schowka',
        softwareDdeveloper: 'Programista oprogramowania',
        openDrawer: 'Otwórz szufladę',
        closeDrawer: 'Zamknij szufladę',
        technicalSchool: 'Technikum Mechatroniczne',
        university: 'Uniwersytet Bielsko-Biała',
        downloadResume: 'Pobierz CV',
        seeInNewTabResume: 'Zobacz CV w nowej karcie',
        techStack: 'Technologie',
        resume: 'CV',
        langISO: 'pl-PL',
        education: 'Edukacja',
        resumeLoadingError: 'Wystąpił błąd podczas ładowania CV',
        showModelIn3D: 'Pokaż model w 3D',
        universitySpecialization: 'Specjalizacja',
        universityStart: 'Rozpoczęcie',
        universityEnd: 'Zakończenie',
        mechatronics: 'Mechatronika',
        technicalSchoolStart: 'Początek technikum',
        technicalSchoolEnd: 'Koniec technikum',
        loadingIsTakingTooLong: 'Ładowanie trwa powyżej',
    },
    us: {
        langCode: 'us',
        langName: 'English',
        langDirection: 'ltr',
        contact: 'Contact',
        profile: 'Profile',
        projects: 'Projects',
        greenPurple: 'Green-purple',
        bluePink: 'Blue-pink',
        myProjects: 'My projects',
        lightTheme: 'Light theme',
        createdBy: 'Created by',
        profileDescription: 'I am a computer science student at Wrocław University of Science and Technology. I am interested in programming, computer graphics and photography.',
        myAccounts: 'My accounts',
        author: 'Adrian Raszka',
        seeOnGithub: 'See on Github',
        createdAt: 'Created at',
        lastCommit: 'Last commit',
        seeRepositoryOnGithub: 'See repository on Github',
        seeUserOnGithub: 'See user on Github',
        repositoryLinkCopiedToClipboard: 'Repository link copied to clipboard',
        softwareDdeveloper: 'Software developer',
        openDrawer: 'Open drawer',
        closeDrawer: 'Close drawer',
        technicalSchool: 'Technical Mechatronics School',
        university: 'University of Bielsko-Biała',
        downloadResume: 'Download CV',
        seeInNewTabResume: 'See CV in new tab',
        techStack: 'Technologies',
        resume: 'Resume',
        langISO: 'en-US',
        education: 'Education',
        resumeLoadingError: 'An error occurred while loading the resume',
        showModelIn3D: 'Show model in 3D',
        universitySpecialization: 'Specialization',
        universityEnd: 'End',
        universityStart: 'Start',
        mechatronics: 'Mechatronics',
        technicalSchoolStart: 'Technical school start',
        technicalSchoolEnd: 'Technical school end',
        loadingIsTakingTooLong: 'Loading is taking above',
    },
    sp: {
        langCode: 'sp',
        langName: 'Español',
        langDirection: 'ltr',
        contact: 'Contacto',
        profile: 'Perfil',
        projects: 'Proyectos',
        greenPurple: 'Verde-púrpura',
        bluePink: 'Azul-rosa',
        myProjects: 'Mis proyectos',
        lightTheme: 'Tema claro',
        createdBy: 'Creado por',
        profileDescription: 'Soy estudiante de informática en la Universidad de Ciencia y Tecnología de Wrocław. Me interesa la programación, los gráficos por computadora y la fotografía.',
        myAccounts: 'Mis cuentas',
        author: 'Adrian Raszka',
        seeOnGithub: 'Ver en Github',
        createdAt: 'Creado en',
        lastCommit: 'Último commit',
        seeRepositoryOnGithub: 'Ver repositorio en Github',
        seeUserOnGithub: 'Ver usuario en Github',
        repositoryLinkCopiedToClipboard: 'Enlace del repositorio copiado al portapapeles',
        softwareDdeveloper: 'Desarrollador de software',
        closeDrawer: 'Cerrar cajón',
        openDrawer: 'Abrir cajón',
        technicalSchool: 'Escuela Técnica de Mecatrónica',
        university: 'Universidad de Bielsko-Biała',
        downloadResume: 'Descargar CV',
        seeInNewTabResume: 'Ver CV en nueva pestaña',
        techStack: 'Tecnologías',
        resume: 'CV',
        langISO: 'es-ES',
        education: 'Educación',
        resumeLoadingError: 'Se produjo un error al cargar el CV',
        showModelIn3D: 'Mostrar modelo en 3D',
        universitySpecialization: 'Especialización',
        universityStart: 'Inicio',
        universityEnd: 'Fin',
        mechatronics: 'Mecatrónica',
        technicalSchoolStart: 'Inicio de la escuela técnica',
        technicalSchoolEnd: 'Fin de la escuela técnica',
        loadingIsTakingTooLong: 'La carga está tomando más de',
    },
    sa: {
        langCode: 'sa',
        langName: 'العربية',
        langDirection: 'rtl',
        contact: 'اتصل',
        profile: 'الملف الشخصي',
        projects: 'مشاريع',
        greenPurple: 'أخضر-أرجواني',
        bluePink: 'أزرق-وردي',
        myProjects: 'مشاريعي',
        lightTheme: 'موضوع الضوء',
        createdBy: 'أنشئ بواسطة',
        profileDescription: 'أنا طالب في علوم الكمبيوتر في جامعة وروكلاو للعلوم والتكنولوجيا. أنا مهتم بالبرمجة والرسومات الكمبيوتر والتصوير الفوتوغرافي.',
        myAccounts: 'حساباتي',
        author: 'أدريان راسزكا',
        seeOnGithub: 'انظر على Github',
        createdAt: 'أنشئت في',
        lastCommit: 'آخر التزام',
        seeRepositoryOnGithub: 'انظر المستودع على Github',
        seeUserOnGithub: 'انظر المستخدم على Github',
        repositoryLinkCopiedToClipboard: 'تم نسخ رابط المستودع إلى الحافظة',
        softwareDdeveloper: 'مطور برامج',
        closeDrawer: 'إغلاق الدرج',
        openDrawer: 'فتح الدرج',
        technicalSchool: 'المدرسة التقنية للميكاترونيك',
        university: 'جامعة بيلسكو-بيالا',
        downloadResume: 'تحميل السيرة الذاتية',
        seeInNewTabResume: 'انظر السيرة الذاتية في علامة تبويب جديدة',
        techStack: 'التكنولوجيا',
        resume: 'السيرة الذاتية',
        langISO: 'ar-SA',
        education: 'التعليم',
        resumeLoadingError: 'حدث خطأ أثناء تحميل السيرة الذاتية',
        showModelIn3D: 'عرض النموذج ثلاثي الأبعاد',
        universitySpecialization: 'تخصص',
        universityStart: 'بداية',
        universityEnd: 'نهاية',
        mechatronics: 'الميكاترونيات',
        technicalSchoolStart: 'بداية المدرسة التقنية',
        technicalSchoolEnd: 'نهاية المدرسة التقنية',
        loadingIsTakingTooLong: 'التحميل يستغرق أكثر من',
    },
}